---
name: CGI-Compress-Gzip
version: 0.20
author:
  - Clotho Advanced Media, I<cpan@clotho.com>
abstract: CGI with automatically compressed output
license: perl
requires:
  CGI: 2.00
  IO::Zlib: 1.01
build_requires:
  Test::More: 0.01
provides:
  CGI::Compress::Gzip:
    file: lib/CGI/Compress/Gzip.pm
    version: 0.20
  CGI::Compress::Gzip::wrapper:
    file: lib/CGI/Compress/Gzip.pm
    version: 0.20
generated_by: Module::Build version 0.2609
