--- #YAML:1.0
name: CGI-Compress-Gzip
version: 0.15
license: restrictive
distribution_type: module
requires:
  CGI: 2.00
  IO::Zlib: 1.01
recommends: {}
build_requires:
  Test::More: 0.01
conflicts: {}
provides:
  CGI::Compress::Gzip:
    file: lib/CGI/Compress/Gzip.pm
    version: 0.15
  CGI::Compress::Gzip::wrapper:
    file: lib/CGI/Compress/Gzip.pm
    version: 0.15
generated_by: Module::Build version 0.21
